spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret-key: giofi2y84782rhifhfkhy283y82hkehyri84y1

app:
  frontend:
    url: http://localhost:8080/frontend
